; Script generated by Antigravity for ClassTrack Desktop Camera Node
; Inno Setup 6 Script

#define MyAppName "ClassTrack Camera Node"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "ClassTrack"
#define MyAppExeName "ClassTrack.exe"

#ifndef AppSourceDir
#define AppSourceDir "..\dist\ClassTrack"
#endif

[Setup]
AppId={{5A8C9B3D-12E4-4F8A-9A21-7890BCDEF123}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\ClassTrack
DefaultGroupName=ClassTrack
DisableProgramGroupPage=yes
OutputDir=..\dist\installer
OutputBaseFilename=ClassTrack_Setup_v1.0
SetupIconFile=assets\app_icon.ico
UninstallDisplayIcon={app}\{#MyAppExeName}
Compression=lzma2/fast
SolidCompression=yes
LZMANumBlockThreads=6
LZMAUseSeparateProcess=yes
WizardStyle=modern
PrivilegesRequired=lowest
CloseApplications=yes
RestartApplications=no

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
Source: "{#AppSourceDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon; IconFilename: "{app}\{#MyAppExeName}"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
